// Code generated by go-swagger; DO NOT EDIT.

package todos

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CreateOneHandlerFunc turns a function with the right signature into a create one handler
type CreateOneHandlerFunc func(CreateOneParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateOneHandlerFunc) Handle(params CreateOneParams) middleware.Responder {
	return fn(params)
}

// CreateOneHandler interface for that can handle valid create one params
type CreateOneHandler interface {
	Handle(CreateOneParams) middleware.Responder
}

// NewCreateOne creates a new http.Handler for the create one operation
func NewCreateOne(ctx *middleware.Context, handler CreateOneHandler) *CreateOne {
	return &CreateOne{Context: ctx, Handler: handler}
}

/*CreateOne swagger:route POST / todos createOne

CreateOne create one API

*/
type CreateOne struct {
	Context *middleware.Context
	Handler CreateOneHandler
}

func (o *CreateOne) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreateOneParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
