// Code generated by go-swagger; DO NOT EDIT.

package todos

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/axard/todo-list/internal/restmodels"
)

// ReadTodosOKCode is the HTTP code returned for type ReadTodosOK
const ReadTodosOKCode int = 200

/*ReadTodosOK Список дел

swagger:response readTodosOK
*/
type ReadTodosOK struct {

	/*
	  In: Body
	*/
	Payload *restmodels.Itemlist `json:"body,omitempty"`
}

// NewReadTodosOK creates ReadTodosOK with default headers values
func NewReadTodosOK() *ReadTodosOK {

	return &ReadTodosOK{}
}

// WithPayload adds the payload to the read todos o k response
func (o *ReadTodosOK) WithPayload(payload *restmodels.Itemlist) *ReadTodosOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the read todos o k response
func (o *ReadTodosOK) SetPayload(payload *restmodels.Itemlist) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ReadTodosOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*ReadTodosDefault Ошибка

swagger:response readTodosDefault
*/
type ReadTodosDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *restmodels.Error `json:"body,omitempty"`
}

// NewReadTodosDefault creates ReadTodosDefault with default headers values
func NewReadTodosDefault(code int) *ReadTodosDefault {
	if code <= 0 {
		code = 500
	}

	return &ReadTodosDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the read todos default response
func (o *ReadTodosDefault) WithStatusCode(code int) *ReadTodosDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the read todos default response
func (o *ReadTodosDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the read todos default response
func (o *ReadTodosDefault) WithPayload(payload *restmodels.Error) *ReadTodosDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the read todos default response
func (o *ReadTodosDefault) SetPayload(payload *restmodels.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ReadTodosDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
