// Code generated by go-swagger; DO NOT EDIT.

package todos

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/axard/todo-list/internal/restmodels"
)

// CreateOneReader is a Reader for the CreateOne structure.
type CreateOneReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateOneReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateOneCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewCreateOneDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCreateOneCreated creates a CreateOneCreated with default headers values
func NewCreateOneCreated() *CreateOneCreated {
	return &CreateOneCreated{}
}

/*CreateOneCreated handles this case with default header values.

Создано
*/
type CreateOneCreated struct {
	Payload *restmodels.Item
}

func (o *CreateOneCreated) Error() string {
	return fmt.Sprintf("[POST /][%d] createOneCreated  %+v", 201, o.Payload)
}

func (o *CreateOneCreated) GetPayload() *restmodels.Item {
	return o.Payload
}

func (o *CreateOneCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(restmodels.Item)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateOneDefault creates a CreateOneDefault with default headers values
func NewCreateOneDefault(code int) *CreateOneDefault {
	return &CreateOneDefault{
		_statusCode: code,
	}
}

/*CreateOneDefault handles this case with default header values.

Ошибка
*/
type CreateOneDefault struct {
	_statusCode int

	Payload *restmodels.Error
}

// Code gets the status code for the create one default response
func (o *CreateOneDefault) Code() int {
	return o._statusCode
}

func (o *CreateOneDefault) Error() string {
	return fmt.Sprintf("[POST /][%d] createOne default  %+v", o._statusCode, o.Payload)
}

func (o *CreateOneDefault) GetPayload() *restmodels.Error {
	return o.Payload
}

func (o *CreateOneDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(restmodels.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
