// Code generated by go-swagger; DO NOT EDIT.

package todos

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/axard/todo-list/internal/restmodels"
)

// NewCreateOneParams creates a new CreateOneParams object
// with the default values initialized.
func NewCreateOneParams() *CreateOneParams {
	var ()
	return &CreateOneParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateOneParamsWithTimeout creates a new CreateOneParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateOneParamsWithTimeout(timeout time.Duration) *CreateOneParams {
	var ()
	return &CreateOneParams{

		timeout: timeout,
	}
}

// NewCreateOneParamsWithContext creates a new CreateOneParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateOneParamsWithContext(ctx context.Context) *CreateOneParams {
	var ()
	return &CreateOneParams{

		Context: ctx,
	}
}

// NewCreateOneParamsWithHTTPClient creates a new CreateOneParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateOneParamsWithHTTPClient(client *http.Client) *CreateOneParams {
	var ()
	return &CreateOneParams{
		HTTPClient: client,
	}
}

/*CreateOneParams contains all the parameters to send to the API endpoint
for the create one operation typically these are written to a http.Request
*/
type CreateOneParams struct {

	/*Body*/
	Body *restmodels.Item

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create one params
func (o *CreateOneParams) WithTimeout(timeout time.Duration) *CreateOneParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create one params
func (o *CreateOneParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create one params
func (o *CreateOneParams) WithContext(ctx context.Context) *CreateOneParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create one params
func (o *CreateOneParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create one params
func (o *CreateOneParams) WithHTTPClient(client *http.Client) *CreateOneParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create one params
func (o *CreateOneParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create one params
func (o *CreateOneParams) WithBody(body *restmodels.Item) *CreateOneParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create one params
func (o *CreateOneParams) SetBody(body *restmodels.Item) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateOneParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
