swagger: "2.0"
info:
  description: From the todo list tutorial on goswagger.io
  title: A Todo list application
  version: 1.0.0
consumes:
- application/io.goswagger.examples.todo-list.v1+json
produces:
- application/io.goswagger.examples.todo-list.v1+json
schemes:
- http
paths:
  /:
    post:
      tags:
        - todos
      operationId: createOne
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/item"
      responses:
        201:
          description: Создано
          schema:
            $ref: "#/definitions/item"
        default:
          description: Ошибка
          schema:
            $ref: "#/definitions/error"
    get:
      tags:
        - todos
      operationId: readTodos
      parameters:
        - name: since
          in: query
          type: integer
          format: int64
        - name: limit
          in: query
          type: integer
          format: int32
          default: 20
      responses:
        200:
          description: Список дел
          schema:
            $ref: "#/definitions/itemlist"
        default:
          description: Ошибка
          schema:
            $ref: "#/definitions/error"
  /{id}:
    parameters:
      - type: integer
        format: int64
        name: id
        in: path
        required: true
    put:
      tags: ["todos"]
      operationId: updateOne
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/item"
      responses:
        '200':
          description: Ок
          schema:
            $ref: "#/definitions/item"
        default:
          description: Ошибка
          schema:
            $ref: "#/definitions/error"
    delete:
      tags:
        - todos
      operationId: deleteOne
      responses:
        204:
          description: Удалено
        default:
          description: Ошибка
          schema:
            $ref: "#/definitions/error"
definitions:
  item:
    type: object
    required:
      - description
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
      description:
        type: string
        minLength: 1
      completed:
        type: boolean
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
  itemlist:
    type: object
    required:
      - items
      - total
    properties:
      items:
        type: array
        items:
          $ref: "#/definitions/item"
      total:
        type: integer
        format: int64
